/**
 * Static dashboard cache fetcher.
 *
 * R730 publishes hourly JSON snapshots over Tailscale Funnel:
 *   <upstream>/stats.json          → HailLeadsStats + generated_at
 *   <upstream>/default_leads.json  → HailLeadListResponse + generated_at
 *
 * The browser cannot reach `*.ts.net` directly from a public-internet
 * origin — Chrome's Private Network Access policy blocks the request
 * even though CORS headers are set. So we route through a same-origin
 * Vercel route handler at `/api/dashboard-cache/<file>` which fetches
 * the upstream server-side.
 *
 * This is the *primary* data source on first paint. We only fall
 * through to the live Railway API when the user changes filters. If the
 * cache itself is unreachable we fall back to hardcoded constants so
 * the dashboard never renders blank.
 *
 * `NEXT_PUBLIC_DASHBOARD_CACHE_BASE` defaults to the same-origin proxy.
 * Override only if you have a reason to bypass it (e.g. local dev with
 * `LAN-direct` Tailscale access, or a CDN edge in front of the cron).
 */

import type {
  HailLeadListItem,
  HailLeadListResponse,
  HailLeadsStats,
} from "./types";

// On the client we hit the same-origin Next route handler so we don't run
// into Chrome's Private Network Access blocker (Tailscale Funnel resolves
// to a private/local IP). On the server (Vercel function) we call the
// upstream directly — no PNA boundary.
const UPSTREAM_BASE =
  process.env.DASHBOARD_CACHE_UPSTREAM ??
  process.env.NEXT_PUBLIC_DASHBOARD_CACHE_UPSTREAM ??
  "https://soc-api.tailad2d5f.ts.net/dashboard-cache";

const CLIENT_BASE =
  process.env.NEXT_PUBLIC_DASHBOARD_CACHE_BASE ?? "/api/dashboard-cache";

const IS_SERVER = typeof window === "undefined";

// File extension policy: same-origin proxy paths use `/stats` (no ext),
// direct upstream paths use `/stats.json`.
function fileUrl(name: "stats" | "default_leads"): string {
  if (IS_SERVER) return `${UPSTREAM_BASE}/${name}.json`;
  const base = CLIENT_BASE;
  return /^https?:\/\//i.test(base)
    ? `${base}/${name}.json`
    : `${base}/${name}`;
}

export type CachedHailLeadsStats = HailLeadsStats & { generated_at?: string };
export type CachedHailLeadListResponse = HailLeadListResponse & {
  generated_at?: string;
};

// ---------------------------------------------------------------------------
// Hardcoded fallback — only used when BOTH the cache and API fail.
// Keep these numbers reasonable for marketing demos.
// ---------------------------------------------------------------------------

export const FALLBACK_STATS: CachedHailLeadsStats = {
  total_leads: 19_700_000,
  unique_addresses: 852_000,
  counties_covered: 115,
  latest_storm_date: "2026-04-26",
  fresh_leads_this_week: 2_300,
  hail_events_last_year: 1_380,
};

export const FALLBACK_LEADS: CachedHailLeadListResponse = {
  results: [],
  total: -1,
  page: 1,
  page_size: 50,
  total_pages: -1,
};

// ---------------------------------------------------------------------------
// Coercion helpers. The cache is generated by Postgres `row_to_json`, which
// emits numerics as strings (e.g. `"hail_size_inches": "1.25"`) and keeps
// the rest of the shape compatible with HailLeadListItem.
// ---------------------------------------------------------------------------

function toNumberOrNull(v: unknown): number | null {
  if (v === null || v === undefined || v === "") return null;
  const n = typeof v === "number" ? v : Number(v);
  return Number.isFinite(n) ? n : null;
}

function coerceLeadItem(raw: Record<string, unknown>): HailLeadListItem {
  return {
    lead_id: String(raw.lead_id ?? ""),
    address: (raw.address as string | null) ?? null,
    city: (raw.city as string | null) ?? null,
    zip: (raw.zip as string | null) ?? null,
    county: (raw.county as string | null) ?? null,
    storm_date: (raw.storm_date as string | null) ?? null,
    storm_type: (raw.storm_type as string | null) ?? null,
    hail_size_inches: toNumberOrNull(raw.hail_size_inches),
    permit_date: (raw.permit_date as string | null) ?? null,
    days_after_storm: toNumberOrNull(raw.days_after_storm),
    lead_category: (raw.lead_category as string | null) ?? null,
    permit_description: (raw.permit_description as string | null) ?? null,
    competitor_contractor: (raw.competitor_contractor as string | null) ?? null,
    score: toNumberOrNull(raw.score),
    prior_roof_permits: toNumberOrNull(raw.prior_roof_permits),
    last_roof_permit_date: (raw.last_roof_permit_date as string | null) ?? null,
    owner_enriched: Boolean(raw.owner_enriched),
  };
}

// ---------------------------------------------------------------------------
// Public fetchers
// ---------------------------------------------------------------------------

async function fetchJson<T>(url: string, signal?: AbortSignal): Promise<T> {
  const res = await fetch(url, {
    headers: { Accept: "application/json" },
    cache: "default",
    signal: signal ?? AbortSignal.timeout(5_000),
  });
  if (!res.ok) {
    throw new Error(`Cache ${res.status} ${res.statusText}`);
  }
  return (await res.json()) as T;
}

export async function getCachedStats(
  signal?: AbortSignal,
): Promise<CachedHailLeadsStats> {
  try {
    const raw = await fetchJson<Record<string, unknown>>(
      fileUrl("stats"),
      signal,
    );
    return {
      total_leads: toNumberOrNull(raw.total_leads) ?? FALLBACK_STATS.total_leads,
      unique_addresses:
        toNumberOrNull(raw.unique_addresses) ??
        FALLBACK_STATS.unique_addresses,
      counties_covered:
        toNumberOrNull(raw.counties_covered) ??
        FALLBACK_STATS.counties_covered,
      latest_storm_date:
        (raw.latest_storm_date as string | null) ??
        FALLBACK_STATS.latest_storm_date,
      fresh_leads_this_week:
        toNumberOrNull(raw.fresh_leads_this_week) ??
        FALLBACK_STATS.fresh_leads_this_week,
      hail_events_last_year:
        toNumberOrNull(raw.hail_events_last_year) ??
        FALLBACK_STATS.hail_events_last_year,
      generated_at: (raw.generated_at as string | undefined) ?? undefined,
    };
  } catch {
    return FALLBACK_STATS;
  }
}

export async function getCachedDefaultLeads(
  signal?: AbortSignal,
): Promise<CachedHailLeadListResponse> {
  try {
    const raw = await fetchJson<Record<string, unknown>>(
      fileUrl("default_leads"),
      signal,
    );
    const rawResults = Array.isArray(raw.results)
      ? (raw.results as Record<string, unknown>[])
      : [];
    return {
      results: rawResults.map(coerceLeadItem),
      total: toNumberOrNull(raw.total) ?? -1,
      page: toNumberOrNull(raw.page) ?? 1,
      page_size: toNumberOrNull(raw.page_size) ?? 50,
      total_pages: toNumberOrNull(raw.total_pages) ?? -1,
      generated_at: (raw.generated_at as string | undefined) ?? undefined,
    };
  } catch {
    return FALLBACK_LEADS;
  }
}
